name: test
on:
  - push
  - pull_request
jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
          - 20
          - 22
          - 24
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - if: contains(matrix.os, 'ubuntu')
        run: sudo apt-get install libjpeg-dev -y
      - if: contains(matrix.os, 'macos')
        run: brew install jpeg
      - if: contains(matrix.os, 'ubuntu')
        run: sudo apt-get install libpng-dev -y
      - if: contains(matrix.os, 'macos')
        run: brew install libpng
      - run: npm install
      - run: npm test
